[workspace]
release_always = true
release = false
pr_name = "release {{ package }}-v{{ version }}"

# Remove agntcy- from git tag and release names
git_tag_name = "{{ package | replace(from='agntcy-', to='') }}-v{{ version }}"
git_release_name = "{{ package | replace(from='agntcy-', to='') }} v{{ version }}"

[[package]]
name = "agntcy-slim-mcp-proxy"
publish = true
release = true
changelog_update = true
