[project]
name = "mcp-slim-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = ["mcp==1.6.0", "anyio>=4.5", "slim-mcp>=0.1.0"]

[tool.uv.sources]
slim-mcp = { path = "../../../slim-mcp/packages/slim-mcp" }
