# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-rust

on:
  push:
    branches:
      - main

jobs:
  # Release unpublished packages.
  release-crates:
    name: Release slim crates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          workspace: .
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
          manifest_path: ./Cargo.toml
          config: ./.release-plz.toml
        env:
          GITHUB_TOKEN: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-crates-pr:
    name: Release slim crates - PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          workspace: .
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
          manifest_path: ./Cargo.toml
          config: ./.release-plz.toml
        env:
          GITHUB_TOKEN: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
